# Generated by Django 4.2.21 on 2025-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0095_fix_related_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="is_mask_issue",
            field=models.BooleanField(default=False),
        ),
    ]
